### ISSUE TITLE
请问tensorflow使用的是什么版本？

### ISSUE THREAD

**Issue by silhouettesia** [DeepLJH0001/DCASE2016#1]
谢谢~

**Comment by DeepLJH0001** [comment]
主要是keras的吧。TensorFlow做backed需要修改配置文件。论文昨天刚被拒了，你还是参考dcase2017的吧，这个数据集的实验太旧了。

**Comment by silhouettesia** [comment]
soga没仔细看😂谢谢~
dcase2017肯定也是要做的，但最近刚上手想看看有没有什么可以借鉴的（然而并没找到哈哈...）
