### ISSUE TITLE
运行dcnn_train时遇到的问题

### ISSUE THREAD

**Issue by yyydoing** [DeepLJH0001/DCASE2016#2]
load_all_dev_data ok!
(182520, 'frame_x samples')
(1170, 'scene_x samples')
Traceback (most recent call last):
  File "dcnn_train.py", line 206, in <module>
    data, label = load_dev_traindata()
**ValueError: too many values to unpack**
想问一下这个问题是什么，load_dev_traindata() return的是“return frame_x, scene_x, frame_y, scene_y”  然后这句“data, label = load_dev_traindata()”赋值出现问题，该怎么解决？

我还想请教一下scene_x = np.empty((len(scene_y), 1, 64, 2584)这儿2584是什么意思？你是使用滑动窗口16像素为单位进行采样的是吗

**Comment by DeepLJH0001** [comment]
返回参数过多，应该只要取frame的数据和标签，因为模型训练的是这个frame的数据，最后做投票。2584是一张mel能量谱的width，窗移可以自己设置，我好像窗长是64。我的mel滤波器设置的是64个三角带通滤波器，产生的frame片段是64*64的mel图。你大概理解一下。。。

**Comment by yyydoing** [comment]
恩，你训练要多久呀，我那天试了一下一天才跑了十几epoch，这样跑的话50epoch要跑6天....

**Comment by DeepLJH0001** [comment]
嗯，要用显卡的。我的gtx1070大概10分钟。话说你是不是我们老师的学生呀。。。。
